# Generated by Django 2.2.1 on 2019-09-14 15:30

from django.db import migrations, models
import predict_inceptionV3.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=predict_inceptionV3.models.nameFile)),
            ],
        ),
    ]
